"""add_columns_to_daily_stats

Revision ID: cde12b0a71be
Revises: 
Create Date: 2026-03-05 02:48:47.616371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde12b0a71be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='Ayar anahtarı: APP_LINK, SLOGAN, DISCLAIMER, vb.'),
    sa.Column('value', sa.Text(), nullable=False, comment='Ayar değeri'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('auto_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_tweet_id', sa.String(length=30), nullable=False, comment='Yanit verilen tweet ID'),
    sa.Column('target_username', sa.String(length=50), nullable=False, comment='Tweet sahibi'),
    sa.Column('target_text', sa.Text(), nullable=False, comment='Orijinal tweet metni'),
    sa.Column('reply_text', sa.Text(), nullable=False, comment='Gonderilen reply'),
    sa.Column('reply_tweet_id', sa.String(length=30), nullable=True, comment="X'teki reply tweet ID"),
    sa.Column('status', sa.String(length=20), nullable=False, comment='replied / failed / skipped / unsafe'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_replies_target_tweet_id'), 'auto_replies', ['target_tweet_id'], unique=True)
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False, comment='Puan miktari'),
    sa.Column('max_uses', sa.Integer(), nullable=False, comment='Maks kullanim sayisi'),
    sa.Column('uses_count', sa.Integer(), nullable=False, comment='Mevcut kullanim sayisi'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Son kullanma tarihi (None=sinirsiz)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Aktif mi'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('daily_stock_market_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False, comment='Hisse kodu, orn: EGEGY'),
    sa.Column('date', sa.Date(), nullable=False, comment='Islem gunu tarihi'),
    sa.Column('close_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Gun sonu kapanis fiyati'),
    sa.Column('percent_change', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False, comment='Gunluk yuzde degisim'),
    sa.Column('is_ceiling', sa.Boolean(), nullable=False, comment='Tavan (>= 9.75%) kapatti mi?'),
    sa.Column('is_floor', sa.Boolean(), nullable=False, comment='Taban (<= -9.75%) kapatti mi?'),
    sa.Column('consecutive_ceiling_count', sa.Integer(), nullable=False, comment='Pes pese kac gundur tavan?'),
    sa.Column('monthly_ceiling_count', sa.Integer(), nullable=False, comment='Son 1 ayda (30 gun) kacinci tavani?'),
    sa.Column('consecutive_floor_count', sa.Integer(), nullable=False, comment='Pes pese kac gundur taban?'),
    sa.Column('monthly_floor_count', sa.Integer(), nullable=False, comment='Son 1 ayda (30 gun) kacinci tabani?'),
    sa.Column('reason', sa.Text(), nullable=True, comment='AI (Sonnet/Abacus) tarafindan uretilen kisa yukselis/dusus sebebi'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_market_stat_date', 'daily_stock_market_stats', ['date'], unique=False)
    op.create_index('idx_daily_market_stat_ticker', 'daily_stock_market_stats', ['ticker'], unique=False)
    op.create_index('idx_daily_mk_stat_ticker_date', 'daily_stock_market_stats', ['ticker', 'date'], unique=True)
    op.create_table('deleted_ipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False, comment='Silinen sirket adi'),
    sa.Column('ticker', sa.String(length=10), nullable=True, comment='Silinen hisse kodu'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Silinme zamani'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividend_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False, comment='Hisse kodu'),
    sa.Column('payment_year', sa.Integer(), nullable=False, comment='Temettu odeme yili'),
    sa.Column('gross_dividend_per_share', sa.Numeric(precision=10, scale=4), nullable=True, comment='Brut hisse basi temettu (TL)'),
    sa.Column('net_dividend_per_share', sa.Numeric(precision=10, scale=4), nullable=True, comment='Net hisse basi temettu (TL)'),
    sa.Column('dividend_yield_pct', sa.Numeric(precision=8, scale=2), nullable=True, comment='Temettu verimi (%)'),
    sa.Column('ex_dividend_date', sa.Date(), nullable=True, comment='Temettu hakedis tarihi (ex-date)'),
    sa.Column('payment_date', sa.Date(), nullable=True, comment='Temettu odeme tarihi'),
    sa.Column('record_date', sa.Date(), nullable=True, comment='Kayit tarihi (record date)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_divhist_ticker_year', 'dividend_history', ['ticker', 'payment_year'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False, comment='Hisse kodu, orn: TUPRS'),
    sa.Column('company_name', sa.Text(), nullable=True, comment='Sirket adi'),
    sa.Column('expected_dividend_yield_pct', sa.Numeric(precision=8, scale=2), nullable=True, comment='Gelecek yil temettu beklentisi (%)'),
    sa.Column('expected_year', sa.Integer(), nullable=True, comment='Beklenti yili, orn: 2027'),
    sa.Column('last_year_yield_pct', sa.Numeric(precision=8, scale=2), nullable=True, comment='Son yil temettu verimi (%)'),
    sa.Column('avg_2y_yield_pct', sa.Numeric(precision=8, scale=2), nullable=True, comment='2 yillik ortalama temettu verimi (%)'),
    sa.Column('avg_3y_yield_pct', sa.Numeric(precision=8, scale=2), nullable=True, comment='3 yillik ortalama temettu verimi (%)'),
    sa.Column('pd_dd', sa.Numeric(precision=8, scale=2), nullable=True, comment='PD/DD — Piyasa Degeri / Defter Degeri'),
    sa.Column('fk', sa.Numeric(precision=8, scale=2), nullable=True, comment='F/K — Fiyat / Kazanc'),
    sa.Column('ytd_return_pct', sa.Numeric(precision=8, scale=2), nullable=True, comment='Yilbasi getiri (%)'),
    sa.Column('yearly_return_pct', sa.Numeric(precision=8, scale=2), nullable=True, comment='Yillik getiri (%)'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='Veri kaynagi'),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Verinin cekildigi tarih'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dividend_expected_yield', 'dividends', ['expected_dividend_yield_pct'], unique=False)
    op.create_index('idx_dividend_ticker', 'dividends', ['ticker'], unique=False)
    op.create_table('feature_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True, comment='Cihaz ID'),
    sa.Column('feature_name', sa.String(length=100), nullable=False, comment='Özellik adı (bilanco_analizi vb.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_interests_feature_name'), 'feature_interests', ['feature_name'], unique=False)
    op.create_table('ipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False, comment='Sirket adi'),
    sa.Column('ticker', sa.String(length=10), nullable=True, comment='Borsa kodu, orn: ATATR'),
    sa.Column('logo_url', sa.Text(), nullable=True, comment='Sirket logo URL'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='newly_approved, in_distribution, awaiting_trading, trading, archived (eski: upcoming, active, completed)'),
    sa.Column('ipo_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Halka arz fiyati (TL)'),
    sa.Column('total_lots', sa.BigInteger(), nullable=True, comment='Toplam pay miktari (lot)'),
    sa.Column('offering_size_tl', sa.Numeric(precision=18, scale=2), nullable=True, comment='Arz buyuklugu (TL)'),
    sa.Column('capital_increase_lots', sa.BigInteger(), nullable=True, comment='Sermaye artirimi (lot)'),
    sa.Column('partner_sale_lots', sa.BigInteger(), nullable=True, comment='Ortak satisi (lot)'),
    sa.Column('subscription_start', sa.Date(), nullable=True, comment='Basvuru baslangic tarihi'),
    sa.Column('subscription_end', sa.Date(), nullable=True, comment='Basvuru bitis tarihi'),
    sa.Column('subscription_hours', sa.String(length=30), nullable=True, comment='Basvuru saatleri, orn: 09:00-17:00'),
    sa.Column('trading_start', sa.Date(), nullable=True, comment='Borsada islem baslangic tarihi'),
    sa.Column('spk_approval_date', sa.Date(), nullable=True, comment='SPK onay tarihi'),
    sa.Column('expected_trading_date', sa.Date(), nullable=True, comment='Beklenen islem baslangic tarihi'),
    sa.Column('spk_bulletin_no', sa.String(length=50), nullable=True, comment='SPK bulteni numarasi, orn: 2026/5'),
    sa.Column('distribution_completed', sa.Boolean(), nullable=False, comment='Dagitim tamamlandi mi'),
    sa.Column('distribution_method', sa.String(length=50), nullable=True, comment='Dagitim yontemi kodu: esit, bireysele_esit, tamami_esit, oransal, karma'),
    sa.Column('distribution_description', sa.Text(), nullable=True, comment='Dagitim yontemi aciklama: Kucuk yatirimciya anlasilir dilde aciklama'),
    sa.Column('participation_method', sa.String(length=30), nullable=True, comment='Katilim yontemi: talep_toplama, borsada_satis'),
    sa.Column('participation_description', sa.Text(), nullable=True, comment='Katilim yontemi aciklama: Kullaniciya anlasilir dilde nasil basvurulur'),
    sa.Column('public_float_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Halka aciklik orani (%)'),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Iskonto orani (%)'),
    sa.Column('market_segment', sa.String(length=30), nullable=True, comment='yildiz_pazar, ana_pazar, alt_pazar'),
    sa.Column('lead_broker', sa.Text(), nullable=True, comment='Konsorsiyum lideri araci kurum'),
    sa.Column('estimated_lots_per_person', sa.Integer(), nullable=True, comment='Tahmini kisi basi lot (500K katilimci varsayimi, Gedik kaynakli)'),
    sa.Column('lock_up_period_days', sa.Integer(), nullable=True, comment='Satmama taahhut suresi (gun)'),
    sa.Column('price_stability_days', sa.Integer(), nullable=True, comment='Fiyat istikrari suresi (gun)'),
    sa.Column('min_application_lot', sa.Integer(), nullable=True, comment='Minimum basvuru lotu'),
    sa.Column('katilim_endeksi', sa.String(length=20), nullable=True, comment='Katilim endeksine uygunluk: uygun, uygun_degil'),
    sa.Column('company_description', sa.Text(), nullable=True, comment='Sirket tanitim metni'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='Sektor'),
    sa.Column('fund_usage', sa.Text(), nullable=True, comment='Fon kullanim hedefleri (JSON)'),
    sa.Column('revenue_current_year', sa.Numeric(precision=18, scale=2), nullable=True, comment='Guncel yil hasilat'),
    sa.Column('revenue_previous_year', sa.Numeric(precision=18, scale=2), nullable=True, comment='Onceki yil hasilat'),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=True, comment='Brut kar'),
    sa.Column('kap_notification_url', sa.Text(), nullable=True, comment='KAP bildirim linki'),
    sa.Column('prospectus_url', sa.Text(), nullable=True, comment='Izahname PDF linki'),
    sa.Column('spk_bulletin_url', sa.Text(), nullable=True, comment='SPK bulteni linki'),
    sa.Column('allocation_announced', sa.Boolean(), nullable=False),
    sa.Column('total_applicants', sa.Integer(), nullable=True, comment='Toplam basvuran sayisi'),
    sa.Column('result_bireysel_kisi', sa.Integer(), nullable=True, comment='Yurt ici bireysel basvuran sayisi'),
    sa.Column('result_bireysel_lot', sa.BigInteger(), nullable=True, comment='Yurt ici bireysel dagitilan lot'),
    sa.Column('ceiling_tracking_active', sa.Boolean(), nullable=False),
    sa.Column('first_day_close_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ceiling_broken', sa.Boolean(), nullable=False),
    sa.Column('ceiling_broken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False, comment='25 is gunu gecti mi'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='Arsiv tarihi'),
    sa.Column('trading_day_count', sa.Integer(), nullable=False, comment='Mevcut islem gunu sayaci'),
    sa.Column('high_from_start', sa.Numeric(precision=12, scale=2), nullable=True, comment='Islem basindan bu yana en yuksek fiyat (%4 dusus hesabi icin)'),
    sa.Column('ai_report', sa.Text(), nullable=True, comment='AI halka arz degerlendirme raporu (JSON)'),
    sa.Column('ai_report_generated_at', sa.DateTime(timezone=True), nullable=True, comment='AI rapor uretim zamani'),
    sa.Column('prospectus_analysis', sa.Text(), nullable=True, comment='İzahname AI analizi (JSON: positives, negatives, summary, risk_level)'),
    sa.Column('prospectus_analyzed_at', sa.DateTime(timezone=True), nullable=True, comment='İzahname analiz zamani'),
    sa.Column('prospectus_tweeted', sa.Boolean(), nullable=False, comment='İzahname analiz tweeti atildi mi'),
    sa.Column('intro_tweeted', sa.Boolean(), nullable=False, comment='Sirket tanitim tweeti atildi mi'),
    sa.Column('distribution_tweeted', sa.Boolean(), nullable=False, comment='Dagitim baslangic tweeti atildi mi (deploy-safe dedup)'),
    sa.Column('last_day_tweeted', sa.Boolean(), server_default='false', nullable=False, comment='Son gun sabah tweeti atildi mi (deploy-safe dedup)'),
    sa.Column('last_day_notified', sa.Boolean(), server_default='false', nullable=False, comment='Son gun push bildirimi gonderildi mi (deploy-safe dedup)'),
    sa.Column('manual_fields', sa.Text(), nullable=True, comment='Admin tarafindan elle duzenlenen alanlar (JSON list). Bot bu alanlari ezmez.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ipos_status', 'ipos', ['status'], unique=False)
    op.create_index('idx_ipos_subscription_end', 'ipos', ['subscription_end'], unique=False)
    op.create_index('idx_ipos_ticker', 'ipos', ['ticker'], unique=False)
    op.create_table('kap_all_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(length=10), nullable=False, comment='Hisse kodu, orn: THYAO'),
    sa.Column('title', sa.Text(), nullable=False, comment='Bildirim basligi'),
    sa.Column('body', sa.Text(), nullable=True, comment='Tam bildirim metni (scrape edilen)'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Kategori: Bilanco, Temettu, Ozel Durum, vb.'),
    sa.Column('is_bilanco', sa.Boolean(), nullable=False, comment='Bilanco/Finansal Rapor bildirimi mi (blur icin)'),
    sa.Column('kap_url', sa.Text(), nullable=True, comment='KAP bildirim linki (kap.org.tr/tr/Bildirim/XXX)'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='Kaynak: bigpara, bloomberght'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Orijinal yayin zamani'),
    sa.Column('ai_sentiment', sa.String(length=10), nullable=True, comment='Olumlu, Olumsuz, Notr'),
    sa.Column('ai_impact_score', sa.Float(), nullable=True, comment='AI etki puani (0.0-10.0)'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI tarafindan uretilen Turkce ozet'),
    sa.Column('ai_analyzed_at', sa.DateTime(timezone=True), nullable=True, comment='AI analiz zamani'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code', 'title', name='uq_kap_company_title')
    )
    op.create_index('idx_kap_all_company', 'kap_all_disclosures', ['company_code'], unique=False)
    op.create_index('idx_kap_all_created', 'kap_all_disclosures', ['created_at'], unique=False)
    op.create_index('idx_kap_all_published', 'kap_all_disclosures', ['published_at'], unique=False)
    op.create_index('idx_kap_all_sentiment', 'kap_all_disclosures', ['ai_sentiment'], unique=False)
    op.create_table('kap_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False, comment='Hisse kodu'),
    sa.Column('kap_notification_id', sa.String(length=20), nullable=True, comment='KAP bildirim ID'),
    sa.Column('price_at_time', sa.Numeric(precision=12, scale=2), nullable=True, comment='Haber anindaki fiyat'),
    sa.Column('news_title', sa.Text(), nullable=True, comment='KAP bildirim basligi'),
    sa.Column('news_detail', sa.Text(), nullable=True, comment='Iliskilendirilen haber detayi'),
    sa.Column('matched_keyword', sa.Text(), nullable=True, comment='Eslesen anahtar kelime'),
    sa.Column('news_type', sa.String(length=20), nullable=False, comment='seans_ici, seans_disi'),
    sa.Column('sentiment', sa.String(length=10), nullable=False, comment='positive, negative, neutral'),
    sa.Column('raw_text', sa.Text(), nullable=True, comment='KAP orijinal bildirim metni'),
    sa.Column('kap_url', sa.Text(), nullable=True, comment='KAP bildirim linki'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='KAP yayinlanma zamani'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_created', 'kap_news', ['created_at'], unique=False)
    op.create_index('idx_news_sentiment', 'kap_news', ['sentiment'], unique=False)
    op.create_index('idx_news_ticker', 'kap_news', ['ticker'], unique=False)
    op.create_index('idx_news_type', 'kap_news', ['news_type'], unique=False)
    op.create_table('pending_tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False, comment='tweet_bist30_news, tweet_new_ipo, tweet_daily_tracking, vs.'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, approved, rejected, sent, failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='X kullanici adi (@ olmadan)'),
    sa.Column('twitter_user_id', sa.String(length=30), nullable=True, comment='Twitter API user ID (cache)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Aktif mi'),
    sa.Column('last_seen_tweet_id', sa.String(length=30), nullable=True, comment='Son gorulmus tweet ID — bundan onceki tweetlere reply atilmaz'),
    sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True, comment='Son reply zamani — 1 saat cooldown icin'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_targets_username'), 'reply_targets', ['username'], unique=True)
    op.create_table('scraper_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_state_key'), 'scraper_state', ['key'], unique=True)
    op.create_table('spk_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False, comment='Ortaklik adi'),
    sa.Column('existing_capital', sa.Numeric(precision=18, scale=2), nullable=True, comment='Mevcut Sermaye (TL)'),
    sa.Column('new_capital', sa.Numeric(precision=18, scale=2), nullable=True, comment='Yeni Sermaye (TL)'),
    sa.Column('capital_increase_paid', sa.Numeric(precision=18, scale=2), nullable=True, comment='Sermaye Artirimi - Bedelli (TL)'),
    sa.Column('capital_increase_free', sa.Numeric(precision=18, scale=2), nullable=True, comment='Sermaye Artirimi - Bedelsiz (TL)'),
    sa.Column('existing_share_sale', sa.Numeric(precision=18, scale=2), nullable=True, comment='Mevcut Ortak Pay Satisi (TL)'),
    sa.Column('additional_share_sale', sa.Numeric(precision=18, scale=2), nullable=True, comment='Ek Pay Satisi (TL)'),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Satis fiyati (TL)'),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=True, comment='SPK basvuru tarihi'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Dipnotlar / aciklamalar'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending: onay bekliyor, approved: onaylandi, rejected: reddedildi, deleted: admin sildi (tekrar eklenmez)'),
    sa.Column('notified', sa.Boolean(), server_default='false', nullable=False, comment='Push bildirim gonderildi mi'),
    sa.Column('tweeted', sa.Boolean(), server_default='false', nullable=False, comment='Tweet atildi mi'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spk_app_company', 'spk_applications', ['company_name'], unique=False)
    op.create_index('idx_spk_app_status', 'spk_applications', ['status'], unique=False)
    op.create_table('telegram_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False, comment='Telegram mesaj ID (tekrari engellemek icin)'),
    sa.Column('chat_id', sa.String(length=50), nullable=False, comment='Telegram chat/kanal ID'),
    sa.Column('message_type', sa.String(length=30), nullable=False, comment='seans_ici_pozitif, seans_ici_negatif, borsa_kapali, seans_disi_acilis'),
    sa.Column('ticker', sa.String(length=10), nullable=True, comment='Hisse kodu, orn: DAPGM'),
    sa.Column('price_at_time', sa.Numeric(precision=12, scale=2), nullable=True, comment='Anlik fiyat'),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='Ham mesaj metni'),
    sa.Column('parsed_title', sa.Text(), nullable=True, comment='Parse edilmis baslik'),
    sa.Column('parsed_body', sa.Text(), nullable=True, comment='Parse edilmis icerik'),
    sa.Column('sentiment', sa.String(length=10), nullable=True, comment='positive, negative, neutral'),
    sa.Column('kap_notification_id', sa.String(length=20), nullable=True, comment='KAP haber ID'),
    sa.Column('expected_trading_date', sa.Date(), nullable=True, comment='Beklenen islem gunu (borsa_kapali tipi icin)'),
    sa.Column('gap_pct', sa.Numeric(precision=6, scale=2), nullable=True, comment='Acilis gap yuzde (seans_disi_acilis tipi icin)'),
    sa.Column('prev_close_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Onceki kapanis fiyati'),
    sa.Column('theoretical_open', sa.Numeric(precision=12, scale=2), nullable=True, comment='Teorik acilis fiyati'),
    sa.Column('ai_score', sa.Float(), nullable=True, comment='AI puan (1.0-10.0, ondalik, yuksek=olumlu)'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI tarafindan uretilen 2 cumle ozet'),
    sa.Column('kap_url', sa.Text(), nullable=True, comment='KAP bildirim linki veya TradingView linki'),
    sa.Column('message_date', sa.DateTime(timezone=True), nullable=True, comment='Telegram mesaj zamani'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_message_id')
    )
    op.create_index('idx_telegram_news_created', 'telegram_news', ['created_at'], unique=False)
    op.create_index('idx_telegram_news_msg_id', 'telegram_news', ['telegram_message_id'], unique=True)
    op.create_index('idx_telegram_news_ticker', 'telegram_news', ['ticker'], unique=False)
    op.create_index('idx_telegram_news_type', 'telegram_news', ['message_type'], unique=False)
    op.create_table('user_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False, comment='Kullanici cihaz ID (users.device_id FK)'),
    sa.Column('ticker', sa.String(length=10), nullable=False, comment='Takip edilen hisse kodu, orn: THYAO'),
    sa.Column('notification_preference', sa.String(length=20), nullable=False, comment='Bildirim tercihi: both, positive_only, negative_only'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_device', 'user_watchlist', ['device_id'], unique=False)
    op.create_index('idx_watchlist_ticker', 'user_watchlist', ['ticker'], unique=False)
    op.create_index('idx_watchlist_unique', 'user_watchlist', ['device_id', 'ticker'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False, comment='Benzersiz cihaz ID'),
    sa.Column('persistent_id', sa.String(length=255), nullable=True, comment='Kalici cihaz ID (Android ID / iOS Keychain). Silip yukleme sonrasi hesap kurtarma icin.'),
    sa.Column('fcm_token', sa.Text(), nullable=True, comment='Firebase push token'),
    sa.Column('expo_push_token', sa.String(length=255), nullable=True, comment='Expo Push Token (ExponentPushToken[...])'),
    sa.Column('platform', sa.String(length=10), nullable=True, comment='ios, android'),
    sa.Column('app_version', sa.String(length=20), nullable=True, comment='Uygulama versiyonu'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='Tum bildirimleri ac/kapat'),
    sa.Column('notify_new_ipo', sa.Boolean(), nullable=False, comment='Yeni halka arz bildirimi'),
    sa.Column('notify_ipo_start', sa.Boolean(), nullable=False, comment='Basvuru basladi bildirimi'),
    sa.Column('notify_ipo_last_day', sa.Boolean(), nullable=False, comment='Son gun uyarisi'),
    sa.Column('notify_ipo_result', sa.Boolean(), nullable=False, comment='Tahsisat sonucu'),
    sa.Column('notify_ceiling_break', sa.Boolean(), nullable=False, comment='Tavan bozuldu bildirimi'),
    sa.Column('notify_first_trading_day', sa.Boolean(), nullable=False, comment='Ilk islem gunu bildirimi (ucretsiz)'),
    sa.Column('notify_kap_bist30', sa.Boolean(), nullable=False, comment='BIST 30 KAP ucretsiz bildirim'),
    sa.Column('notify_kap_all', sa.Boolean(), nullable=False, comment='Tum KAP haber bildirimi (ucretli aboneler)'),
    sa.Column('notify_taban_break', sa.Boolean(), nullable=False, comment='Taban acilinca bildirimi'),
    sa.Column('notify_daily_open_close', sa.Boolean(), nullable=False, comment='Gunluk acilis kapanis bildirimi'),
    sa.Column('notify_percent_drop', sa.Boolean(), nullable=False, comment='Yuzde dusus bildirimi'),
    sa.Column('notify_kap_watchlist', sa.Boolean(), nullable=False, comment='KAP takip listesi bildirimleri'),
    sa.Column('reminder_30min', sa.Boolean(), nullable=False, comment='Son gune 30 dk kala'),
    sa.Column('reminder_1h', sa.Boolean(), nullable=False, comment='Son gune 1 saat kala'),
    sa.Column('reminder_2h', sa.Boolean(), nullable=False, comment='Son gune 2 saat kala'),
    sa.Column('reminder_4h', sa.Boolean(), nullable=False, comment='Son gune 4 saat kala'),
    sa.Column('wallet_balance', sa.Float(), nullable=False, comment='Puan bakiyesi'),
    sa.Column('daily_ads_watched', sa.Integer(), nullable=False, comment='Bugun izlenen reklam sayisi'),
    sa.Column('last_ad_watched_at', sa.DateTime(timezone=True), nullable=True, comment='Son reklam izleme zamani'),
    sa.Column('ads_reset_date', sa.String(length=20), nullable=True, comment='Gunluk reklam sayaci tarihi (YYYY-MM-DD)'),
    sa.Column('last_daily_checkin', sa.String(length=20), nullable=True, comment='Son gunluk giris puan tarihi (YYYY-MM-DD)'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='Kullanici hesabini sildi'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Silme talep tarihi'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('persistent_id')
    )
    op.create_table('ceiling_track_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=True, comment='IPO silinirse abonelik korunur'),
    sa.Column('tier', sa.String(length=10), nullable=False, comment='5_gun, 10_gun, 15_gun, 20_gun'),
    sa.Column('tracking_days', sa.Integer(), nullable=False, comment='Kac gun takip edilecek (5/10/15/20)'),
    sa.Column('price_paid_tl', sa.Numeric(precision=8, scale=2), nullable=False, comment='Odenen fiyat (TL)'),
    sa.Column('revenue_cat_id', sa.String(length=255), nullable=True),
    sa.Column('store', sa.String(length=20), nullable=True, comment='app_store, play_store'),
    sa.Column('product_id', sa.String(length=100), nullable=True, comment='Store product ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Takip bitis tarihi'),
    sa.Column('notified_count', sa.Integer(), nullable=False, comment='Gonderilen bildirim sayisi'),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ceiling_sub_active', 'ceiling_track_subscriptions', ['is_active'], unique=False)
    op.create_index('idx_ceiling_sub_user_ipo', 'ceiling_track_subscriptions', ['user_id', 'ipo_id'], unique=False)
    op.create_table('ipo_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False, comment='bireysel, yuksek_basvurulu, kurumsal_yurtici, kurumsal_yurtdisi'),
    sa.Column('allocation_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Tahsisat orani (%)'),
    sa.Column('allocated_lots', sa.BigInteger(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True, comment='Basvuran sayisi (sonuc)'),
    sa.Column('avg_lot_per_person', sa.Numeric(precision=10, scale=2), nullable=True, comment='Kisi basina ort lot (sonuc)'),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipo_brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.Text(), nullable=False),
    sa.Column('broker_type', sa.String(length=20), nullable=True, comment='banka, araci_kurum, konsorsiyum'),
    sa.Column('is_rejected', sa.Boolean(), nullable=False, comment='True = basvurulamaz (ustu cizili)'),
    sa.Column('application_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipo_ceiling_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('trading_day', sa.Integer(), nullable=False, comment='1-20 arasi islem gunu'),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Acilis fiyati'),
    sa.Column('close_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Kapanis fiyati'),
    sa.Column('high_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Gun ici en yuksek'),
    sa.Column('low_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Gun ici en dusuk'),
    sa.Column('hit_ceiling', sa.Boolean(), nullable=False, comment='Tavan yaptı mi'),
    sa.Column('hit_floor', sa.Boolean(), nullable=False, comment='Taban yapti mi'),
    sa.Column('ceiling_broken_at', sa.DateTime(timezone=True), nullable=True, comment='Tavan bozulma zamani'),
    sa.Column('floor_hit_at', sa.DateTime(timezone=True), nullable=True, comment='Tabana kitlenme zamani'),
    sa.Column('relocked', sa.Boolean(), nullable=False, comment='Tekrar tavana kitledi mi'),
    sa.Column('relocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_ceiling_break', sa.Boolean(), nullable=False),
    sa.Column('notified_relock', sa.Boolean(), nullable=False),
    sa.Column('notified_floor', sa.Boolean(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False, comment='tavan, alici_kapatti, not_kapatti, satici_kapatti, taban'),
    sa.Column('pct_change', sa.Numeric(precision=10, scale=2), nullable=True, comment='Gunluk % degisim (onceki gun kapanisina gore)'),
    sa.Column('alis_lot', sa.Integer(), nullable=True, comment='1. kademe alis lotu'),
    sa.Column('satis_lot', sa.Integer(), nullable=True, comment='1. kademe satis lotu'),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ceiling_ipo_day', 'ipo_ceiling_tracks', ['ipo_id', 'trading_day'], unique=True)
    op.create_table('stock_notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=True, comment='NULL ise yillik paket (tum hisseler). IPO silinirse abonelik korunur.'),
    sa.Column('notification_type', sa.String(length=30), nullable=False, comment='tavan_bozulma, taban_acilma, gunluk_acilis_kapanis, yuzde_dusus'),
    sa.Column('is_annual_bundle', sa.Boolean(), nullable=False, comment='Paket mi? (quarterly/semiannual/annual)'),
    sa.Column('custom_percentage', sa.Integer(), nullable=True, comment='Yuzde dusus icin kullanicinin sectigi oran (1-9)'),
    sa.Column('price_paid_tl', sa.Numeric(precision=8, scale=2), nullable=False, comment='Odenen fiyat (TL)'),
    sa.Column('revenue_cat_id', sa.String(length=255), nullable=True),
    sa.Column('store', sa.String(length=20), nullable=True, comment='app_store, play_store'),
    sa.Column('product_id', sa.String(length=100), nullable=True, comment='Store product ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_count', sa.Integer(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False, comment='Kullanici tek tusla sessiz moda alabilir'),
    sa.Column('muted_types', sa.Text(), nullable=True, comment='Bundle icin tip bazli mute — JSON array'),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_notif_active', 'stock_notification_subscriptions', ['is_active'], unique=False)
    op.create_index('idx_stock_notif_type', 'stock_notification_subscriptions', ['notification_type'], unique=False)
    op.create_index('idx_stock_notif_user_ipo', 'stock_notification_subscriptions', ['user_id', 'ipo_id'], unique=False)
    op.create_table('user_ipo_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ipo_id', sa.Integer(), nullable=False),
    sa.Column('notify_last_day', sa.Boolean(), nullable=False),
    sa.Column('notify_result', sa.Boolean(), nullable=False),
    sa.Column('notify_ceiling', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_ipo_alert', 'user_ipo_alerts', ['user_id', 'ipo_id'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package', sa.String(length=20), nullable=False, comment='free, bist100, yildiz_pazar, ana_yildiz'),
    sa.Column('revenue_cat_id', sa.String(length=255), nullable=True, comment='RevenueCat subscriber ID'),
    sa.Column('store', sa.String(length=20), nullable=True, comment='app_store, play_store'),
    sa.Column('product_id', sa.String(length=100), nullable=True, comment='Store product ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False, comment='Islem miktari (pozitif=kazanc, negatif=harcama)'),
    sa.Column('tx_type', sa.String(length=30), nullable=False, comment='ad_reward, coupon, spend_news, spend_ipo, spend_notif'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Islem aciklamasi'),
    sa.Column('balance_after', sa.Float(), nullable=False, comment='Islem sonrasi bakiye'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_tx_type', 'wallet_transactions', ['tx_type'], unique=False)
    op.create_index('idx_wallet_tx_user', 'wallet_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wallet_tx_user', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_type', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_table('user_subscriptions')
    op.drop_index('idx_user_ipo_alert', table_name='user_ipo_alerts')
    op.drop_table('user_ipo_alerts')
    op.drop_index('idx_stock_notif_user_ipo', table_name='stock_notification_subscriptions')
    op.drop_index('idx_stock_notif_type', table_name='stock_notification_subscriptions')
    op.drop_index('idx_stock_notif_active', table_name='stock_notification_subscriptions')
    op.drop_table('stock_notification_subscriptions')
    op.drop_index('idx_ceiling_ipo_day', table_name='ipo_ceiling_tracks')
    op.drop_table('ipo_ceiling_tracks')
    op.drop_table('ipo_brokers')
    op.drop_table('ipo_allocations')
    op.drop_index('idx_ceiling_sub_user_ipo', table_name='ceiling_track_subscriptions')
    op.drop_index('idx_ceiling_sub_active', table_name='ceiling_track_subscriptions')
    op.drop_table('ceiling_track_subscriptions')
    op.drop_table('users')
    op.drop_index('idx_watchlist_unique', table_name='user_watchlist')
    op.drop_index('idx_watchlist_ticker', table_name='user_watchlist')
    op.drop_index('idx_watchlist_device', table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_index('idx_telegram_news_type', table_name='telegram_news')
    op.drop_index('idx_telegram_news_ticker', table_name='telegram_news')
    op.drop_index('idx_telegram_news_msg_id', table_name='telegram_news')
    op.drop_index('idx_telegram_news_created', table_name='telegram_news')
    op.drop_table('telegram_news')
    op.drop_index('idx_spk_app_status', table_name='spk_applications')
    op.drop_index('idx_spk_app_company', table_name='spk_applications')
    op.drop_table('spk_applications')
    op.drop_index(op.f('ix_scraper_state_key'), table_name='scraper_state')
    op.drop_table('scraper_state')
    op.drop_index(op.f('ix_reply_targets_username'), table_name='reply_targets')
    op.drop_table('reply_targets')
    op.drop_table('pending_tweets')
    op.drop_index('idx_news_type', table_name='kap_news')
    op.drop_index('idx_news_ticker', table_name='kap_news')
    op.drop_index('idx_news_sentiment', table_name='kap_news')
    op.drop_index('idx_news_created', table_name='kap_news')
    op.drop_table('kap_news')
    op.drop_index('idx_kap_all_sentiment', table_name='kap_all_disclosures')
    op.drop_index('idx_kap_all_published', table_name='kap_all_disclosures')
    op.drop_index('idx_kap_all_created', table_name='kap_all_disclosures')
    op.drop_index('idx_kap_all_company', table_name='kap_all_disclosures')
    op.drop_table('kap_all_disclosures')
    op.drop_index('idx_ipos_ticker', table_name='ipos')
    op.drop_index('idx_ipos_subscription_end', table_name='ipos')
    op.drop_index('idx_ipos_status', table_name='ipos')
    op.drop_table('ipos')
    op.drop_index(op.f('ix_feature_interests_feature_name'), table_name='feature_interests')
    op.drop_table('feature_interests')
    op.drop_index('idx_dividend_ticker', table_name='dividends')
    op.drop_index('idx_dividend_expected_yield', table_name='dividends')
    op.drop_table('dividends')
    op.drop_index('idx_divhist_ticker_year', table_name='dividend_history')
    op.drop_table('dividend_history')
    op.drop_table('deleted_ipos')
    op.drop_index('idx_daily_mk_stat_ticker_date', table_name='daily_stock_market_stats')
    op.drop_index('idx_daily_market_stat_ticker', table_name='daily_stock_market_stats')
    op.drop_index('idx_daily_market_stat_date', table_name='daily_stock_market_stats')
    op.drop_table('daily_stock_market_stats')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_auto_replies_target_tweet_id'), table_name='auto_replies')
    op.drop_table('auto_replies')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
